set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_status_modules_right "session user host"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g base-index 1
setw -g pane-base-index 1
setw -g mouse on
set -sg escape-time 0

unbind C-b
set -g prefix C-a
bind-key -n M-! select-window -t 1
bind-key -n M-@ select-window -t 2
bind-key -n M-# select-window -t 3
bind-key -n M-% select-window -t 4
bind-key -n M-^ select-window -t 5
bind-key -n M-& select-window -t 6
bind-key -n M-* select-window -t 7
bind-key -n M-( select-window -t 8
bind-key -n M-) select-window -t 9

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
