#!/bin/bash

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM="wayland-egl"
export SDL_VIDEODRIVER="wayland"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

dbus-run-session sway
