#!/bin/bash

programs_running="false"
nicotine_pid=""
qbittorrent_pid=""

check_vpn_connection() {
	active_vpns=$(ls /sys/class/net/ | grep "wg-mv")
	
	if [[ -z "$active_vpns" ]]
	then
		echo "No VPN connections active - exiting!"
		
		if [[ "$programs_running" == "true" ]]
		then
			kill $nicotine_pid
			kill $qbittorrent_pid
		fi

		exit 1
	fi
}

check_vpn_connection

nicotine &
nicotine_pid=$!

qbittorrent &
qbittorrent_pid=$!

programs_running="true"

while true
do
	check_vpn_connection
	sleep 2
done
