#!/bin/bash

export GTK2_RC_FILES="/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc"
export MOZ_ENABLE_WAYLAND=1
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway

sway
