import = [
	"~/.config/alacritty/onedark.toml"
]

[env]
term = "xterm-256color"

[window]
# decorations = "none"
startup_mode = "Maximized"

[font]
size = 11

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
